name = "music-mcp"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]
routes = [{ pattern = "music.builditwithai.xyz", custom_domain = true }]

[assets]
directory = "public"

[placement]
mode = "smart"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "music-mcp-d1"
database_id = "4c59e95d-87aa-4714-88cb-9c31bc5eb3c7"
migrations_dir = "migrations"

[triggers]
crons = ["0 0 * * *"]

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "music-mcp-vectors"

[vars]
POSTHOG_API_KEY = "phc_Aik6H3pf5P9dPBrWLjd6N3wzsVAD6tJnmmEhFwW8Pzsi"
POSTHOG_HOST = "https://us.i.posthog.com"
